.github/pull_request_template.md, typescript-selenium-webdriver/README.md
An earlier PR removed code coverage build tasks (they are irrelevant to the sample, since the sample has no non-test js/ts code). This updates readme and PR template to match.
=> Remove references to removed code coverage from readme/PR template

typescript-selenium-webdriver/src/index.html, typescript-selenium-webdriver/tests/index.test.ts
When I was experimenting with different types of snapshotting/baselining behavior, I wanted it to be obvious to a non-expert user which detected failures were actually intentional. I thought it was a little more obvious to an unfamiliar reader for the 3 list items that are obviously examples to be the *only* examples caught by the tests.
This fixes the [region](https://dequeuniversity.com/rules/axe/3.2/region) and [landmark-one-main](https://dequeuniversity.com/rules/axe/3.2/landmark-one-main) violations, leaving exactly the one violation per bullet point that the bullet points self-describe.
=> Fix non-obvious index.html issues

typescript-selenium-webdriver/tests/index.test.ts
During development of other snapshot/baselining changes that involved adding multiple test cases, I found that I wanted this wait call to be happening before every test rather than as an isolated sanity check in its own test. Moved it and updated comments accordingly.
=> Move driver.wait to beforeEach instead of separate test

typescript-selenium-webdriver/.vscode/launch.json
Adds standard .vscode launch tasks for debugging the Jest tests, from https://github.com/microsoft/vscode-recipes/tree/master/debugging-jest-tests
I'm undecided on whether it's actually appropriate to include this in the sample repo, since it's not *directly* required for running accessibility tests. Would appreciate reviewers' thoughts on whether we *should* include this, not just whether it's syntactically correct.
=> Add vscode launch.json tasks for Jest debugging

typescript-selenium-webdriver/jest.config.js, typescript-selenium-webdriver/package.json, typescript-selenium-webdriver/tests/index.test.ts, typescript-selenium-webdriver/yarn.lock
Updates jest.config.js to recommend use of the jest-circus runner to enable tests to early-exit when beforeAll/beforeEach methods fail, per facebook/jest#2713
=> use jest-circus runner to improve beforeAll/beforeEach failure behavior

README.md, typescript-selenium-webdriver/README.md, typescript-selenium-webdriver/package.json, typescript-selenium-webdriver/tsconfig.json
Cleans up a few usability issues we caught while doing a demo trial run this afternoon. Specifically:
* Replaces the table in the root readme with a list (JAWS didn't cooperate very well with the table, and it also rendered poorly on mobile)
* Adds a "Getting Started" section to the sample's readme that points the user to particularly notable files to read
* Removes an unnecessary/leftover `tsconfig.json` file
* Removes readme wording suggesting that we've already implemented sarif multitool baselining examples
=> Clean up readme usability issues caught during demo

README.md
For some unknown reason, if the available samples list is formatted like this:
* **[first link](https://example.com)**: text with [more links](https://example.com)
...JAWS and NVDA both skip the first link when navigating by links. But with the bold formatting removed, like this:
* [first link](https://example.com): text with [more links](https://example.com)
...they do not skip it.
=> Readme SR compat: remove bold formatting on link in list

typescript-selenium-webdriver/azure-pipelines.yml
One of the initial users of the sample stumbled a bit on the "Azure Pipelines integration" part. This change updates the comments in the sample to add more context for users that aren't very familiar with Azure Pipelines.
Also makes it a bit more clear that "npm" vs "yarn" doesn't matter, similar to what we did in the readme already.
=> Add comments in azure-pipelines.yml based on initial user feedback

typescript-selenium-webdriver/package.json, typescript-selenium-webdriver/yarn.lock
* Bumps axe-sarif-converter to new major version 2.0.0 to pick up SARIF v2.1.0 output
* `yarn upgrade`s other dependencies to lock on latest minor/patch versions
=> feat: update SARIF output to 2.1.0 via axe-sarif-converter v2.0.0

typescript-selenium-webdriver/README.md
Updates README "Run the tests!" section to run the locally installed jest instead of the globally installed jest
=> fix: update "run tests" instructions to use local instead of global jest

typescript-selenium-webdriver/tests/__snapshots__/index.test.ts.snap, typescript-selenium-webdriver/tests/index.test.ts
add test case to demo case where axe uses specific tags for wcag2 'a' and 'aa'
=> fix: add test case where axe uses specific tags for wcag2 'a' and 'aa'

typescript-selenium-webdriver/tests/index.test.ts
Updates the comments about using a localhost test server to be more perscriptive about recommendations for how to set that up (noting where in the code you would do it and offering examples of libraries to use).
For reviewers: I'm interested both in review of the text change itself, but also review of whether we think updating the comment like this is likely to be sufficient to consider #25 closed. I'm on the fence; I'm not sure we really want a full example with a test server to be in scope for this sample, but I'm also not sure this update will be enough to resolve the user question as is
=> docs: add more detail to comment about localhost test server usage

typescript-selenium-webdriver/tests/index.test.ts
Previously, if the webdriver initialization step in `beforeAll` failed, it would result in `driver` never being set and a spurious failure in `afterAll` attempting to call `driver.quit()` for undefined `driver`. This adds a defensive check to prevent the spurious secondary error message.
=> fix: prevent misleading afterAll failure when driver initialization fails

.github/CODEOWNERS
Just noticed that Ortiga's approval in #56 wasn't being accepted because we've got the wrong team set up as code owners. Updating to use the more general team.
- [n/a] `yarn test` passes in all affected samples
- [n/a] Added any applicable tests
=> chore: use general codeowners team instead of web one

csharp-selenium-webdriver-sample/README.md
Missed updating link to file when we flattened the directory structure.
- [n/a] `yarn test` passes in all affected samples
- [n/a] Added any applicable tests
=> docs: fix broken link to SampleTest.cs in README

csharp-selenium-webdriver-sample/azure-pipelines.yml, typescript-selenium-webdriver-sample/azure-pipelines.yml
Standardizes a few inconsistencies between our sample azure-pipelines.yml files and the official docs' samples:
* Use 2-space indentation throughout
* Put `displayName` in a consistent spot in steps
* Use consistent `displayName` formats between the 2 files
* Use `succeededOrFailed()` rather than `always()` for conditions on test publishing steps
- [n/a] `yarn test` passes in all affected samples
- [n/a] Added any applicable tests
=> chore: standardize azure-pipelines.yml format with each other and per official docs

.dependabot/config.yml
This repo has multiple "root" folders with different languages, so it requires a checked in config file for Dependabot to work correctly.
For docs on this config file, see https://dependabot.com/docs/config-file
I think the only particularly interesting/subjective part of this config is the `version_requirement_updates: increase_versions` on the typescript folder. Essentially, we have to decide whether Dependabot should update package.json in the way it normally would for a library (where it would update yarn.lock but widen version ranges in package.json) or the way it normally would for an app (where it updates package.json to require the newer version). I think the latter makes more sense for a sample but could probably be persuaded otherwise.
I've already run this through the …
=> chore: add Dependabot config file

csharp-selenium-webdriver-sample/CSharpSeleniumWebdriverSample.csproj
Updates both MSTest dependencies in sync with one another to avoid them complaining about mismatching on the breaking 2.0.0 changes.
- [n/a] Added any applicable tests
=> Bump MSTest.* to 2.0.0

.github/pull_request_template.md, csharp-selenium-webdriver-sample/README.md, csharp-selenium-webdriver-sample/SamplePage.html, csharp-selenium-webdriver-sample/SamplePageTests.cs, csharp-selenium-webdriver-sample/azure-pipelines.yml
Addresses a variety of feedback items received in the recent round of user studies for the C# sample. Specifically:
* Moves the test setup/cleanup below the example test methods
* Clarifies which `using` statements a reader is likely to care about
* Adds a TestMethod demonstrating a basic scan of an entire page as the first example test, before the "scan one element in page" example
* Ensures that there is an example test that actually fails in practice, to give a better idea of what a failure would look like
* Clarify how `Include` works before using it incidentally alongside `WithTags`
* Add a more precise/verbose description of what "tags" and "rules" are and how to find more information about them
* clarify that Include/Exclude accept CSS selectors (not just IDs)
* Update sample page …
=> [c#] Address user study feedback in SampleTests.cs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general_question.md
Use comments for help text in issue templates so they don't show up when the issue creator doesn't delete them. The commented help text will still show up during issue creation.
- [n/a] All updated/modified sample code builds and runs in at least one PR/CI build
- [n/a] PR checks for builds named `[failing example] ...` fail as expected
=> chore: update issue templates to use comments for help text

csharp-selenium-webdriver-sample/WebDriverFactory.cs
During local testing of #128, I noticed that the .NET Core + Windows + Firefox environment combination was excessively slow compared to all other combinations (taking >2min per test run instead of <10s).
This turns out to be caused by https://github.com/mozilla/geckodriver/issues/1496 / https://bugzilla.mozilla.org/show_bug.cgi?id=1525659 - if I'm understanding the bugs correctly, geckodriver listens for selenium commands on IPv4 only by default and selenium tries to connect via "http://localhost" rather than "http://127.0.0.1", but .NET Core's standard HttpClient behavior under Windows ends up attempting to connect to "localhost" URLs via IPv6 for a second before timing out and retrying on IPv4, so in practice this adds a second of overhead to every API call between Selenium and …
=> Improve windows dotnet firefox perf

csharp-selenium-webdriver-sample/WebDriverFactory.cs, typescript-selenium-webdriver-sample/tests/webdriver-factory.ts
Per suggestion from @manishsat , this PR has the samples set a default window size explicitly, to avoid issues related to the color contrast test's "scroll into viewport" behavior in the default window sizes used by the browsers' headless modes (eg, https://github.com/dequelabs/axe-core/issues/1730)
I verified the syntax of the window size parameters locally by temporarily disabling the headless options and manually verifying the created window sizes.
=> Set default window sizes

csharp-selenium-webdriver-sample/SamplePageTests.cs, typescript-selenium-webdriver-sample/tests/__snapshots__/index.test.ts.snap, typescript-selenium-webdriver-sample/tests/index.test.ts
This change moves the explanations and usages of the "withTags" axe-core API from their own separate tests up into the first "basic" tests in each sample to address feedback from users that copied the "basic" tests when their results don't match Accessibility Insights'.
=> fix: make use of withTags more prominent to avoid confusion vs Application Insights results

typescript-selenium-webdriver-sample/README.md, typescript-selenium-webdriver-sample/package.json, typescript-selenium-webdriver-sample/tests/index.test.ts, typescript-selenium-webdriver-sample/yarn.lock
This updates the typescript sample to use the updated name for `@axe-core/webdriverjs` (as well as the related libraries we mention the names of in the README). There was one minor code change required as part of the update.
Note, this implicitly updates the version of axe-core in use to 4.0.2 (the sample gets it indirectly via the webdriverjs lib)
=> feat(axe-core-4.0.2): update from axe-webdriverjs to @axe-core/webdriverjs

typescript-selenium-webdriver-sample/jest.config.js, typescript-selenium-webdriver-sample/package.json, typescript-selenium-webdriver-sample/yarn.lock
This PR updates the typescript sample to Jest 27.
* Removes explicit jest-circus and testEnvironment: node settings (these are now Jest's defaults)
* Removes explicit jest-circus dependency (this is now bundled with Jest by default)
* Regenerates lockfile (avoids many double-dependencies on large deps like babel)
There still isn't an updated `@types/jest` package, so we're still pulling in two versions of a few jest support libs, but I wanted to pull in the update now because it's still a net decrease in total dependency tree size.
Keep deps up to date
Obsoletes #560 
=> chore(deps-dev): migrate typescript sample from Jest 26 to Jest 27

typescript-playwright-sample/README.md, typescript-selenium-webdriver-sample/README.md
Per the notice at the top of the old [Sarif Viewer Build Tab extension's marketplace page](https://marketplace.visualstudio.com/items?itemName=sariftools.sarif-viewer-build-tab), it's been deprecated and replaced by the [SARIF SAST Scans Tab](https://marketplace.visualstudio.com/items?itemName=sariftools.scans) extension. This updates the naming/links accordingly.
Both the old and new extensions are currently installed in both our public and private devops organizations (you can see two "Scans" tabs in build results pages because of this). I'll be removing the old one once this PR merges.
Keep deps up to date
Pulled out of #579 
=> fix: update name/link of SARIF scans tab extension

.github/dependabot.yml
I missed adding the new playwright sample to our dependabot config with #579 , this corrects the mistake
Keep deps up to date
see #579 
- [n/a] All updated/modified sample code builds and runs in at least one PR/CI build
=> chore: add playwright sample to dependabot config

typescript-playwright-sample/package.json, typescript-playwright-sample/tests/index.spec.ts, typescript-playwright-sample/yarn.lock
This PR updates `playwright` and `@playwright/test` in sync to 1.13.1. It also includes a bit of manual lockfile regeneration required to keep them in sync. This is required because the two packages include redundant sets of typings; our tests get passed types from the latter but @axe-core/playwright expects types from the former, so the build breaks if they get updated independently.
Keep deps up to date
Obsoletes #602  and #601 
=> chore(deps): bump playwright and @playwright/test to 1.13.1 in sync

typescript-playwright-sample/package.json, typescript-playwright-sample/yarn.lock
Synced update of all playwright refs from 1.13.1 to 1.14.0
This has to be done manually or we end up with mismatched versions between @axe-core/playwright vs direct deps
Obsoletes #612 and #613 
=> chore(deps): typescript-playwright-sample: bump playwright to 1.14.0

typescript-playwright-sample/README.md, typescript-selenium-webdriver-sample/README.md
This fixes typos in two README files
addresses issue #717 
- [n/a] All updated/modified sample code builds and runs in at least one PR/CI build
=> fix: correct accessibility spelling in READMEs

typescript-playwright-sample/README.md, typescript-playwright-sample/azure-pipelines.yml, typescript-playwright-sample/playwright.config.ts, typescript-playwright-sample/tests/export-to-sarif.ts, typescript-playwright-sample/tests/failing-examples.spec.ts, typescript-playwright-sample/tests/passing-examples.spec.ts
This PR implements support for separate passing vs failing example pipelines for `typescript-playwright-sample`, similar to what we already have set up for `csharp-selenium-webdriver-sample`.
I've already set up the pipelines on the Azure DevOps side.
Show off what a real failure might look like in practice
n/a
=> Create a failing example pipeline for typescript-playwright-sample

typescript-playwright-sample/tests/failing-examples.spec.ts, typescript-playwright-sample/tests/passing-examples.spec.ts, typescript-selenium-webdriver-sample/tests/index.test.ts
During last Friday's office hours, one user tried following our samples in a project which was using a test library that provided an `expect` implementation whose `toStrictEqual` assertion worked slightly differently from Jest/`@playwright/test`'s. Our samples use assertions like `expect(axeResults.violations).toStrictEqual([]);` - this works in our samples because that expectation is testing for `===` equality of list members, but in this particular user's case, their test library used something more like `testSubject === []`, which failed with a confusing error (since the two empty lists in question were string-equal and didn't have a diff).
In that user's case, switching to `.toEqual` was the solution. `.toEqual` is an equally valid test assertion for the our Jest/`@playwright/test` …
=> fix: swap typescript assertions from toStrictEqual to toEqual

.github/dependabot.yml, typescript-playwright-sample/azure-pipelines.yml, typescript-playwright-sample/package.json, typescript-playwright-sample/yarn.lock, typescript-selenium-webdriver-sample/azure-pipelines.yml, typescript-selenium-webdriver-sample/package.json, typescript-selenium-webdriver-sample/yarn.lock
This PR updates our Typescript samples to use the current LTS version of node (16.15.0). It also updates node typings (and our dependabot policy for updating them) accordingly.
Keep dependencies up to date
n/a
=> chore(deps): update typescript samples to node 16

typescript-playwright-sample/azure-pipelines.yml
MacOS 10.15 is being phased out as a virtual environment. We're getting the following warnings in our builds:
```
The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583
```
This PR simply changes all instances of `macOS-10.15` to `macOS-11`.
We could use `macOS-latest` to avoid having to touch these files in the future, but deprecations are infrequent and having an explicit version makes it easier to identify cases where tests potentially fail after changing OS versions.
We could use `macOS-12`, but that would leave downlevel clients with no testing in our pipeline. Since most of our internal testing will be on macOS 12 (required for security reasons), using …
=> chore: Update mac environment from 10.15 to 11

.github/pull_request_template.md, csharp-selenium-webdriver-sample/SamplePageTests.cs, typescript-playwright-sample/tests/failing-examples.spec.ts
When first written, we had 2 pipelines that were "failing examples" to show customers what failures look like. However, these pipelines created a lot of friction for dependabot changes, so we added #1237 to streamline the PR approval process. Unfortunately, the user-facing docs use the pipeline as a demo of the failing builds, so this caused a documentaion problem.
One option would be to split the PR and the CLI into 2 distinct pipelines, but that introduces some organizational friction that we'd prefer to avoid. The alternative is to use the same pipeline for both the PR and CI builds, but make them behave differently--tests in PR builds all pass (to streamline the review), while tests in CI builds (i.e., built from the main branch) fail (to provide the doc examples).
The …
=> chore: Make "failing" pipelines pass in PR builds but fail in CI builds

typescript-playwright-sample/package.json, typescript-playwright-sample/yarn.lock
Update to latest version (4.7.2) of `axe-core` package. 
Part of axe-core update feature
The `axe-core/webdriver.js` package has been at version 4.7.3 for some time. If it's important to keep these in sync, we should consider excluding this package from dependabot updates
=> feat: Update to axe-core 4.7.2

typescript-playwright-sample/azure-pipelines.yml, typescript-selenium-webdriver-sample/azure-pipelines.yml
Node 16 is no longer in support. This moves us up to the currently active version of Node
Get on a current version, unblock packages that no longer support Node 16
- [n/a] If this PR addresses an existing issue, it is linked
=> chore: Update to Node 20.x (current LTS version)

.github/dependabot.yml, typescript-playwright-sample/package.json, typescript-playwright-sample/yarn.lock, typescript-selenium-webdriver-sample/package.json, typescript-selenium-webdriver-sample/yarn.lock
#1350 updated to Node 20.x, but dependabot is still locked on 16.x. This PR updates to 20.x and allows dependabot to create PR's for updates as they become available.
@types/node should be on the same major version as node
- [n/a] If this PR addresses an existing issue, it is linked:
=> chore: Update @types/node to match current Node version

csharp-selenium-webdriver-sample/azure-pipelines.yml, typescript-playwright-sample/azure-pipelines.yml, typescript-selenium-webdriver-sample/azure-pipelines.yml
1ES PT adds tags to pipeline runs using the access token provided by ADO. In the case of pipeline runs against forked repos of a GitHub repo, the access token does not have Edit build quality permissions and hence cannot add tags. To unblock those pipelines, skipped tagging by using the option SkipBuildTagsForGitHubPullRequests.
Verified that the only change in the pipeline run is that it do not add "1ES.PT.Unofficial" tag on the Run. In place of that it adds below warning message.
##[warning]1ES PT Warning: Skipping build tags as this build is a pull request form GitHub which does not have permissions to add tags.
- [na] If this PR addresses an existing issue, it is linked: Fixes #0000
- [na] New sample content is commented at a similar verbosity as existing content
- [na] All …
=> fix: Added skip setting for 1ES PT tag in ADO pipeline
